"""Execution agent: assemble the markdown pack and persist into knowledge."""

from datetime import UTC, datetime
from typing import Any, Protocol
from uuid import UUID


class KnowledgePersister(Protocol):
    """Port for writing generated markdown into the workspace knowledge base."""

    async def persist_markdown(
        self,
        *,
        workspace_id: UUID,
        filename: str,
        content: str,
    ) -> UUID:
        """Ingest markdown and return the resulting document id."""

        ...


class ExecutionAgent:
    """Assemble the launch pack and hand it to the knowledge persister."""

    def __init__(self, persister: KnowledgePersister) -> None:
        self.persister = persister

    async def invoke(self, state: dict[str, Any]) -> dict[str, Any]:
        product_name = str(state["product_name"])
        pack_md = assemble_pack(
            product_name=product_name,
            brief=str(state["brief"]),
            research_md=str(state.get("research_md") or ""),
            competitors_md=str(state.get("competitors_md") or ""),
            positioning_md=str(state.get("positioning_md") or ""),
            roadmap_md=str(state.get("roadmap_md") or ""),
            marketing_md=str(state.get("marketing_md") or ""),
            business_model_md=str(state.get("business_model_md") or ""),
            financial_md=str(state.get("financial_md") or ""),
            prd_md=str(state.get("prd_md") or ""),
            tech_spec_md=str(state.get("tech_spec_md") or ""),
            cursor_prompts_md=str(state.get("cursor_prompts_md") or ""),
            linkedin_md=str(state.get("linkedin_md") or ""),
            telegram_md=str(state.get("telegram_md") or ""),
        )
        stamp = datetime.now(UTC).strftime("%Y%m%d")
        slug = _slugify(product_name)
        filename = f"launch-strategy-{slug}-{stamp}.md"
        document_id = await self.persister.persist_markdown(
            workspace_id=UUID(str(state["workspace_id"])),
            filename=filename,
            content=pack_md,
        )
        return {
            "pack_md": pack_md,
            "pack_filename": filename,
            "document_id": str(document_id),
        }


def assemble_pack(
    *,
    product_name: str,
    brief: str,
    research_md: str,
    competitors_md: str,
    positioning_md: str,
    roadmap_md: str,
    marketing_md: str,
    business_model_md: str = "",
    financial_md: str = "",
    prd_md: str = "",
    tech_spec_md: str = "",
    cursor_prompts_md: str = "",
    linkedin_md: str = "",
    telegram_md: str = "",
) -> str:
    """Deterministically merge agent sections into one markdown pack."""

    generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    sections = [
        (f"# Launch Strategy Pack — {product_name}", None),
        ("", None),
        (f"_Generated by Norma AI · {generated_at}_", None),
        ("", None),
        ("## Brief", brief),
        ("## Market research", research_md),
        ("## Competitors", competitors_md),
        ("## Positioning", positioning_md),
        ("## Roadmap", roadmap_md),
        ("## Marketing outline", marketing_md),
        ("## Business model", business_model_md),
        ("## Financial model", financial_md),
        ("## PRD", prd_md),
        ("## Technical specification", tech_spec_md),
        ("## Cursor prompts", cursor_prompts_md),
        ("## LinkedIn content", linkedin_md),
        ("## Telegram content", telegram_md),
    ]
    lines: list[str] = []
    for heading, body in sections:
        if body is None:
            lines.append(heading)
            continue
        lines.extend(
            [
                heading,
                "",
                body.strip() or f"_No {heading.removeprefix('## ').lower()} produced._",
                "",
            ]
        )
    return "\n".join(lines)


def _slugify(value: str) -> str:
    cleaned = "".join(
        char.lower() if char.isalnum() else "-" for char in value.strip()
    )
    while "--" in cleaned:
        cleaned = cleaned.replace("--", "-")
    return cleaned.strip("-")[:48] or "initiative"
